Modify coverage.

diff --git a/.github/workflows/RunTests.yml b/.github/workflows/RunTests.yml
--- a/.github/workflows/RunTests.yml
+++ b/.github/workflows/RunTests.yml
@@ -12,58 +12,64 @@ permissions:
 
 jobs:
   build:
-
-    # TODO split test and publish!
-
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v2
 
-    - name: Setup .NET
-      uses: actions/setup-dotnet@v1
-      with:
-        dotnet-version: 8.0.x
+      - uses: actions/checkout@v2
 
-    # This global tool is required to build Monogame content which is used in a test.
-    - name: Install mgcb
-      run: dotnet tool install dotnet-mgcb --global
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: 8.0.x
 
-    # Grab dependencies like NuGet packages.
-    - name: Restore dependencies
-      run: dotnet restore
-      
-    # Build and test in debug mode:
-    - name: Test
-      run: dotnet test --verbosity normal --logger "trx;LogFileName=test-results.trx" --no-restore --collect:"XPlat Code Coverage"
+      # This global tool is required to build Monogame content which is used in a test.
+      - name: Install mgcb
+        run: dotnet tool install dotnet-mgcb --global
 
-    # Generate a test report.
-    - name: Test Report
-      uses: dorny/test-reporter@v1.7.0
-      if: success() || failure()    # run this step even if previous step failed
-      with:
-        name: Generate test report            # Name of the check run which will be created
-        path: Define*Tests/TestResults/test-results.trx # Path to test results. Note the wildcard.
-        reporter: dotnet-trx        # Format of test results
+      # Grab dependencies like NuGet packages.
+      - name: Restore dependencies
+        run: dotnet restore
+        
+      # Build and test in debug mode:
+      - name: Test
+        run: dotnet test --verbosity normal --logger "trx;LogFileName=test-results.trx" --no-restore
 
-    # Generate code coverage report.
-    - name: Code Coverage Report
-      uses: irongut/CodeCoverageSummary@v1.3.0
-      with:
-        filename: Define*Tests/TestResults/**/coverage.cobertura.xml
-        badge: true
-        fail_below_min: true
-        format: markdown
-        hide_branch_rate: false
-        hide_complexity: true
-        indicators: true
-        output: both
-        thresholds: '60 80'
+      # Generate a test report.
+      - name: Test Report
+        uses: dorny/test-reporter@v1.7.0
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Generate test report            # Name of the check run which will be created
+          path: Define*Tests/TestResults/test-results.trx # Path to test results. Note the wildcard.
+          reporter: dotnet-trx        # Format of test results
 
-    # Post the results of the previous step as a PR comment.
-    - name: Add Coverage PR Comment
-      uses: marocchino/sticky-pull-request-comment@v2.8.0
-      if: github.event_name == 'pull_request'
-      with:
-        recreate: true
-        path: code-coverage-results.md
+      # See this issue here for the reason why I am running test twice:
+      # https://github.com/microsoft/vstest/issues/2334
+      - name: Test (second pass)
+        run: dotnet test --collect:"XPlat Code Coverage" --verbosity normal --no-restore --no-build
+
+      # Generate code coverage report.
+      - name: Code Coverage Report
+        uses: irongut/CodeCoverageSummary@v1.3.0
+        with:
+          filename: Define*Tests/TestResults/*/coverage.cobertura.xml
+          badge: true
+          fail_below_min: true
+          format: markdown
+          hide_branch_rate: false
+          hide_complexity: true
+          indicators: true
+          output: both
+          thresholds: '60 75'
+
+      # Post the results of the previous step as a PR comment.
+      - name: Add Coverage PR Comment
+        uses: marocchino/sticky-pull-request-comment@v2.8.0
+        if: github.event_name == 'pull_request'
+        with:
+          recreate: true
+          path: code-coverage-results.md
+
+      - name: Write coverage to step summary
+        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
